Repository georgberky/dependency-update-maven-plugin, pull requests merged in 2022-10, with the labels that each got.

#57 [#56] Update mockk test dependency to 1.12.8
  pom.xml
Labels: dependencies

#44 #43: Inform user, if new version of an already discovered artifact is available
  .gitpod.Dockerfile
  .gitpod.yml
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/GitProvider.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/JGitProvider.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/NativeGitProvider.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/UpdateMojo.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/VersionUpdate.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/DependencyVersionUpdateTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/GitProviderTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/UpdateMojoIT.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/VersionUpdateTest.kt
  src/test/resources-its/io/github/georgberky/maven/plugins/depsupdate/UpdateMojoIT/remoteBranchForPreviousVersionExists/pom.xml
Labels: feature

#67 Improve Mojo documentation
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/UpdateMojo.kt
Labels: documentation, hacktoberfest

#66 [#11] format source code
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/DependencyExtensions.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/DependencyManagementVersionUpdate.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/DependencyVersionUpdate.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/GitProviderChoice.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/JGitProvider.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/NativeGitProvider.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/ParentVersionUpdate.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/Update.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/UpdateMojo.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/UpdateResolver.kt
  src/main/kotlin/io/github/georgberky/maven/plugins/depsupdate/VersionUpdate.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/ArtifactVersionComparisonTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/ArtifactoryExtensionsKtTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/Bug37NewBranchFromMasterIT.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/DependencyManagementVersionUpdateTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/DependencyVersionUpdateTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/GitProviderTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/JGitProviderTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/NativeGitProviderErrorHandlingTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/NativeGitProviderTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/ParentVersionUpdateTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/PomHelper.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/UpdateMojoIT.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/UpdateMojoNativeGitIT.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/UpdateResolverTest.kt
  src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/VersionUpdateTest.kt
Labels: skip-changelog, hacktoberfest
